import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import styled from "styled-components";
import Link from "next/link";

export default function Home() {
  console.log("top画面作成中");
  const Div = styled.div`
    display: flex;
    flex-direction: column;
    justify-content: center;
  `;
  const Main = styled.main`
    background-color: #eaf0f6;
    text-align: center;
  `;
  const H1 = styled.h1`
    text-align: center;
  `;
  const YouTube = styled.div`
    text-align: center;
  `;
  return (
    <Div>
      <Head>
        <title>にじ歌まとめ(仮)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Main>
        <H1>Welcome to にじ歌まとめ(仮)</H1>
        <p>
          このサイトはにじさんじの歌ってみた動画をまとめたサイトです
        </p>
        <br />
        <h2>今日のおすすめ動画</h2>
        <YouTube>
          <iframe
            width="560"
            height="315"
            src="https://www.youtube.com/embed/3tgCntI4tBs"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
          ></iframe>
        </YouTube>
        <Link href="/vtuber">
          <a>vtuber一覧</a>
        </Link>
      </Main>
    </Div>
  );
}
